### ISSUE TITLE
Registratiepagina fixen

### ISSUE THREAD

**Issue by wslaghekke** [MaxdeMooij/ervarentrainers#8]

**Comment by wslaghekke** [comment]
error word veroorzaakt doordat de velden 
- ervaring
- typeTrainer
- geslacht

 niet zichtbaar zijn, maar nog wel verplicht.
nadenken over hoe we dit aanpakken bij registratie, zijn deze velden bij registratie al verplicht, of gebruiken we een soort van profiel-compleetheid-ding zoals linkedin

**Comment by MaxdeMooij** [comment]
Precies zoals het profiel-compleetheid-ding zoals linkedin. Het zou mooi zijn om de zoek-ranking te baseren op de compleetheid van het profiel.
